import type { Comment, CommentUser, Notification } from "./types";

export const currentUser: CommentUser = {
  id: "u1",
  name: "Sarah Chen",
  initials: "SC",
  role: "reviewer",
  avatarColor: "hsl(207 71% 38%)",
  email: "sarah@countable.com",
};

export const engagementMembers: CommentUser[] = [
  currentUser,
  { id: "u2", name: "James Wilson", initials: "JW", role: "preparer", avatarColor: "hsl(145 63% 42%)", email: "james@countable.com" },
  { id: "u3", name: "Maya Patel", initials: "MP", role: "manager", avatarColor: "hsl(30 90% 50%)", email: "maya@countable.com" },
  { id: "u4", name: "Alex Kim", initials: "AK", role: "preparer", avatarColor: "hsl(270 60% 55%)", email: "alex@countable.com" },
  { id: "u5", name: "David Lee", initials: "DL", role: "read_only", avatarColor: "hsl(350 70% 55%)", email: "david@client.com" },
];

export const mockComments: Comment[] = [
  {
    id: "c1",
    author: engagementMembers[1],
    body: "The AR balance doesn't reconcile with the sub-ledger. Can someone verify the aging schedule?",
    status: "published",
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    mentions: ["u1"],
    replies: [
      {
        id: "r1",
        author: currentUser,
        body: "I'll check the aging report. There might be a timing difference from the December entries.",
        createdAt: new Date(Date.now() - 1000 * 60 * 15),
        mentions: [],
      },
      {
        id: "r2",
        author: engagementMembers[2],
        body: "@James Wilson please also check if the write-offs were posted correctly per CSRS 4200.A12.",
        createdAt: new Date(Date.now() - 1000 * 60 * 5),
        mentions: ["u2"],
      },
    ],
    attachments: [],
    anchor: { screen: "Balance Sheet", section: "Current Assets", lineItem: "Accounts receivable", row: 2, yPosition: 22, xPosition: 78 },
    pinNumber: 1,
  },
  {
    id: "c2",
    author: currentUser,
    body: "Revenue recognition looks correct for Q4. Verified against bank deposits.",
    status: "resolved",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 45),
    resolvedBy: engagementMembers[2],
    mentions: [],
    replies: [],
    attachments: [],
    anchor: { screen: "Statement of Income Loss", section: "Revenue", lineItem: "Sales revenue", row: 1, yPosition: 15, xPosition: 72 },
    pinNumber: 2,
  },
  {
    id: "c3",
    author: engagementMembers[3],
    body: "Need to adjust depreciation on capital assets. The rate was changed mid-year.",
    status: "published",
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
    mentions: ["u1", "u3"],
    replies: [],
    attachments: [
      { id: "a1", name: "depreciation_schedule.pdf", type: "application/pdf", size: 245000, url: "#" },
    ],
    anchor: { screen: "Balance Sheet", section: "Non-Current Assets", lineItem: "Property, plant and equipment", row: 6, yPosition: 55, xPosition: 50 },
    pinNumber: 3,
  },
  {
    id: "c4",
    author: engagementMembers[1],
    body: "Draft note for review — cash flow classifications might need reclassification per new standards.",
    status: "draft",
    createdAt: new Date(Date.now() - 1000 * 60 * 10),
    mentions: [],
    replies: [],
    attachments: [],
    anchor: { screen: "Statement of Cash Flows", section: "Operating Activities", lineItem: "Net cash from operations", row: 1, yPosition: 20, xPosition: 80 },
    pinNumber: 4,
  },
  {
    id: "c5",
    author: engagementMembers[2],
    body: "Cover page formatting approved. Client name and period confirmed.",
    status: "locked",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    lockedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    mentions: [],
    replies: [
      {
        id: "r3",
        author: currentUser,
        body: "Confirmed. Matches the engagement letter.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 23),
        mentions: [],
      },
    ],
    attachments: [],
    anchor: { screen: "Cover Page", section: "Client Name", lineItem: "ABC Pvt. Ltd.", yPosition: 45, xPosition: 50 },
    pinNumber: 5,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "mention",
    fromUser: engagementMembers[1],
    commentId: "c1",
    preview: "The AR balance doesn't reconcile with the sub-ledger...",
    engagementName: "Shipping Line Inc. — COM-CON-Dec312024",
    anchor: { screen: "Balance Sheet", section: "Current Assets", lineItem: "Accounts receivable" },
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: "n2",
    type: "reply",
    fromUser: engagementMembers[2],
    commentId: "c1",
    preview: "@James Wilson please also check if the write-offs...",
    engagementName: "Shipping Line Inc. — COM-CON-Dec312024",
    anchor: { screen: "Balance Sheet", section: "Current Assets", lineItem: "Accounts receivable" },
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: "n3",
    type: "resolved",
    fromUser: engagementMembers[2],
    commentId: "c2",
    preview: "Revenue recognition looks correct for Q4...",
    engagementName: "Shipping Line Inc. — COM-CON-Dec312024",
    anchor: { screen: "Statement of Income Loss", section: "Revenue", lineItem: "Sales revenue" },
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
  },
];
