import React, { useState } from 'react';
import { Download, Flag, AlertTriangle, Info, CheckCircle2, Clock, Plus, Pencil, Trash2, Check, X } from 'lucide-react';
import { Button } from '@/components/wp-ui/button';
import { Badge } from '@/components/wp-ui/badge';
import { StyledCard } from '@/components/wp-ui/card';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/wp-ui/dialog';
import { flagRows as initialFlags } from '../data/investmentData';
import type { FlagRow, FlagPriority, FlagStatus } from '../types/investmentTypes';
import toast from 'react-hot-toast';

const PRIORITY_CFG: Record<FlagPriority, { variant: string; icon: React.ComponentType<{ className?: string }>; color: string }> = {
  HIGH:   { variant: 'destructive', icon: AlertTriangle, color: 'text-red-600'    },
  MEDIUM: { variant: 'warning',     icon: Flag,          color: 'text-amber-600'  },
  LOW:    { variant: 'outline',     icon: Clock,         color: 'text-foreground' },
  INFO:   { variant: 'info',        icon: Info,          color: 'text-blue-600'   },
};
const STATUS_CFG: Record<FlagStatus, { variant: string; label: string }> = {
  Open:     { variant: 'warning', label: 'Open'     },
  Resolved: { variant: 'success', label: 'Resolved' },
  'N/A':    { variant: 'outline', label: 'N/A'      },
};
const PRIORITIES: FlagPriority[] = ['HIGH', 'MEDIUM', 'LOW', 'INFO'];
const STATUSES:   FlagStatus[]   = ['Open', 'Resolved', 'N/A'];

// Inline-cell input styles — global design system (matches Long-term Asset form style)
const BASE = 'input-double-border w-full h-8 text-xs rounded-[10px] border border-[#dcdfe4] bg-white dark:bg-card text-foreground placeholder:text-foreground/60 transition-all duration-200 hover:border-[hsl(210_25%_75%)] dark:border-[hsl(220_15%_30%)] focus:outline-none';
const CI  = `${BASE} px-2.5`;
const CIS = `${BASE} pl-2.5 pr-6 appearance-none cursor-pointer`;

type FlagDraft = Omit<FlagRow, 'id' | 'flagNo'>;

function blankDraft(): FlagDraft {
  return {
    priority: 'MEDIUM', category: '', security: '', ticker: '', broker: '',
    description: '', actionRequired: '', status: 'Open', notes: '', autoGenerated: false,
  };
}

export function InvFlagsTab() {
  const [flags,        setFlags]        = useState<FlagRow[]>(initialFlags);
  const [filterPriority, setFP]         = useState<'All' | FlagPriority>('All');
  const [filterStatus,   setFS]         = useState<'All' | FlagStatus>('All');
  const [editingId,    setEditingId]    = useState<string | null>(null); // 'new' | id | null
  const [draft,        setDraft]        = useState<FlagDraft | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; label: string } | null>(null);

  const upd = (patch: Partial<FlagDraft>) => setDraft(prev => prev ? { ...prev, ...patch } : prev);

  const nextFlagNo = (() => {
    const nums = flags.map(f => parseInt(f.flagNo.replace(/\D/g, ''), 10)).filter(n => !isNaN(n));
    const next  = nums.length > 0 ? Math.max(...nums) + 1 : 1;
    return `FL-${String(next).padStart(2, '0')}`;
  })();

  const startAdd  = () => { setEditingId('new'); setDraft(blankDraft()); };
  const startEdit = (f: FlagRow) => {
    const { id: _id, flagNo: _fn, ...rest } = f;
    setEditingId(f.id);
    setDraft(rest);
  };
  const cancelEdit = () => { setEditingId(null); setDraft(null); };

  const saveRow = () => {
    if (!draft) return;
    if (!draft.category.trim())       { toast.error('Category is required');        return; }
    if (!draft.description.trim())    { toast.error('Description is required');    return; }
    if (!draft.actionRequired.trim()) { toast.error('Action Required is required'); return; }
    if (editingId === 'new') {
      setFlags(prev => [{ id: `FLAG-${Date.now()}`, flagNo: nextFlagNo, ...draft }, ...prev]);
      toast.success(`${nextFlagNo} added`);
    } else {
      setFlags(prev => prev.map(f => f.id === editingId ? { ...f, ...draft } : f));
      toast.success('Flag updated');
    }
    cancelEdit();
  };

  const cycleStatus = (id: string) => {
    if (editingId === id) return;
    setFlags(prev => prev.map(f => {
      if (f.id !== id) return f;
      const next: FlagStatus = f.status === 'Open' ? 'Resolved' : f.status === 'Resolved' ? 'N/A' : 'Open';
      toast.success(`${f.flagNo} marked ${next}`);
      return { ...f, status: next };
    }));
  };

  const confirmDelete = () => {
    if (!deleteTarget) return;
    setFlags(prev => prev.filter(f => f.id !== deleteTarget.id));
    setDeleteTarget(null);
    toast.success('Flag removed');
  };

  const filtered = flags.filter(f =>
    (filterPriority === 'All' || f.priority === filterPriority) &&
    (filterStatus   === 'All' || f.status   === filterStatus)
  );
  const countByPriority = (p: FlagPriority) => flags.filter(f => f.priority === p).length;
  const openCount       = flags.filter(f => f.status === 'Open').length;
  const resolvedCount   = flags.filter(f => f.status === 'Resolved').length;

  const handleExport = async () => {
    try {
      const rows = flags.map(f => ({
        Flag: f.flagNo, Priority: f.priority, Category: f.category,
        Security: f.security ?? '', Ticker: f.ticker ?? '', Broker: f.broker ?? '',
        Description: f.description, 'Action Required': f.actionRequired,
        Status: f.status, Notes: f.notes ?? '',
      }));
      const { exportToExcel, objsToAOA } = await import('../lib/utils');
      exportToExcel({ 'Flags & Review': objsToAOA(rows) }, 'INV_Flags_FY2025.xlsx');
      toast.success('Flags exported');
    } catch { toast.error('Export failed'); }
  };

  // ── Inline edit/add row ──────────────────────────────────────────────────────
  const EditRow = ({ flagNo }: { flagNo: string }) => (
    <tr className="bg-primary/5 border-l-[3px] border-l-primary">
      {/* Flag# */}
      <td className="px-4 py-2">
        <span className="text-xs font-mono font-semibold bg-muted px-1.5 py-0.5 rounded text-foreground/60">{flagNo}</span>
      </td>
      {/* Priority */}
      <td className="px-3 py-2">
        <div className="relative">
          <select className={CIS} value={draft?.priority ?? 'MEDIUM'} onChange={e => upd({ priority: e.target.value as FlagPriority })}>
            {PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
          </select>
        </div>
      </td>
      {/* Category */}
      <td className="px-3 py-2">
        <input className={CI} value={draft?.category ?? ''} onChange={e => upd({ category: e.target.value })}
          placeholder="Category *" />
      </td>
      {/* Security / Ticker / Broker */}
      <td className="px-3 py-2 space-y-0.5">
        <input className={CI} value={draft?.security ?? ''} onChange={e => upd({ security: e.target.value })}
          placeholder="Security" />
        <input className={CI} value={draft?.ticker ?? ''} onChange={e => upd({ ticker: e.target.value.toUpperCase() })}
          placeholder="Ticker" />
        <input className={CI} value={draft?.broker ?? ''} onChange={e => upd({ broker: e.target.value })}
          placeholder="Broker" />
      </td>
      {/* Description */}
      <td className="px-3 py-2">
        <input className={CI} value={draft?.description ?? ''} onChange={e => upd({ description: e.target.value })}
          placeholder="Description *" />
        {/* Notes sub-row */}
        <input className={`${CI} mt-0.5`} value={draft?.notes ?? ''} onChange={e => upd({ notes: e.target.value })}
          placeholder="Notes (optional)" />
      </td>
      {/* Action Required */}
      <td className="px-3 py-2">
        <input className={CI} value={draft?.actionRequired ?? ''} onChange={e => upd({ actionRequired: e.target.value })}
          placeholder="Action required *" />
      </td>
      {/* Status */}
      <td className="px-3 py-2 text-center">
        <div className="relative">
          <select className={CIS} value={draft?.status ?? 'Open'} onChange={e => upd({ status: e.target.value as FlagStatus })}>
            {STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
        </div>
      </td>
      {/* Save / Cancel */}
      <td className="px-2 py-2">
        <div className="flex items-center gap-1">
          <Button size="icon-sm" variant="default" onClick={saveRow} title="Save (Enter)">
            <Check className="w-3 h-3" />
          </Button>
          <Button size="icon-sm" variant="ghost" onClick={cancelEdit} title="Cancel (Esc)">
            <X className="w-3 h-3" />
          </Button>
        </div>
      </td>
    </tr>
  );

  return (
    <div className="p-6 space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-base font-semibold text-foreground">Flags &amp; Review</h2>
          <p className="text-xs text-foreground mt-0.5">
            Workpaper review items — WAC policy, cost basis, withholding tax, and other discrepancies
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" size="sm" onClick={handleExport}>
            <Download className="w-3.5 h-3.5" /> Export
          </Button>
          <Button variant="default" size="sm" onClick={startAdd} disabled={!!editingId}>
            <Plus className="w-3.5 h-3.5" /> Add Flag
          </Button>
        </div>
      </div>

      {/* KPI strip */}
      <div className="grid grid-cols-6 gap-3">
        {(PRIORITIES).map(p => {
          const cfg   = PRIORITY_CFG[p];
          const PIcon = cfg.icon;
          return (
            <StyledCard key={p}
              className={`p-3 flex items-center gap-2 cursor-pointer transition-all ${filterPriority === p ? 'ring-2 ring-primary' : ''}`}
              onClick={() => setFP(prev => prev === p ? 'All' : p)}>
              <PIcon className={`w-5 h-5 ${cfg.color} flex-shrink-0`} />
              <div>
                <div className="text-xl font-bold text-foreground">{countByPriority(p)}</div>
                <div className="text-xs text-foreground">{p}</div>
              </div>
            </StyledCard>
          );
        })}
        <StyledCard className="p-3 flex items-center gap-2 cursor-pointer transition-all col-span-1"
          onClick={() => setFS(prev => prev === 'Open' ? 'All' : 'Open')}>
          <Flag className="w-5 h-5 text-amber-500 flex-shrink-0" />
          <div>
            <div className="text-xl font-bold text-foreground">{openCount}</div>
            <div className="text-xs text-foreground">Open</div>
          </div>
        </StyledCard>
        <StyledCard className="p-3 flex items-center gap-2 cursor-pointer transition-all col-span-1"
          onClick={() => setFS(prev => prev === 'Resolved' ? 'All' : 'Resolved')}>
          <CheckCircle2 className="w-5 h-5 text-green-600 flex-shrink-0" />
          <div>
            <div className="text-xl font-bold text-foreground">{resolvedCount}</div>
            <div className="text-xs text-foreground">Resolved</div>
          </div>
        </StyledCard>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-2 flex-wrap">
        <span className="text-xs text-foreground">Priority:</span>
        {(['All', 'HIGH', 'MEDIUM', 'LOW', 'INFO'] as const).map(p => (
          <button key={p} onClick={() => setFP(p)}
            className={`px-2.5 py-1 text-xs rounded-md border transition-colors ${
              filterPriority === p ? 'bg-primary text-primary-foreground border-primary' : 'border-border hover:bg-muted'
            }`}>{p}</button>
        ))}
        <span className="text-xs text-foreground ml-2">Status:</span>
        {(['All', 'Open', 'Resolved', 'N/A'] as const).map(s => (
          <button key={s} onClick={() => setFS(s)}
            className={`px-2.5 py-1 text-xs rounded-md border transition-colors ${
              filterStatus === s ? 'bg-primary text-primary-foreground border-primary' : 'border-border hover:bg-muted'
            }`}>{s}</button>
        ))}
        {(filterPriority !== 'All' || filterStatus !== 'All') && (
          <button onClick={() => { setFP('All'); setFS('All'); }}
            className="text-xs text-foreground hover:text-foreground underline underline-offset-2 ml-1">Clear</button>
        )}
      </div>

      {/* Table */}
      <StyledCard className="overflow-hidden p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-muted/50">
                <th className="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider text-foreground">Flag</th>
                <th className="text-left px-3 py-3 text-xs font-semibold uppercase tracking-wider text-foreground">Priority</th>
                <th className="text-left px-3 py-3 text-xs font-semibold uppercase tracking-wider text-foreground">Category</th>
                <th className="text-left px-3 py-3 text-xs font-semibold uppercase tracking-wider text-foreground">Security</th>
                <th className="text-left px-3 py-3 text-xs font-semibold uppercase tracking-wider text-foreground min-w-[220px]">Description</th>
                <th className="text-left px-3 py-3 text-xs font-semibold uppercase tracking-wider text-foreground min-w-[200px]">Action Required</th>
                <th className="text-center px-3 py-3 text-xs font-semibold uppercase tracking-wider text-foreground">Status</th>
                <th className="w-16 px-2 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {/* New row inline */}
              {editingId === 'new' && draft && <EditRow flagNo={nextFlagNo} />}

              {filtered.map(f => {
                const pcfg  = PRIORITY_CFG[f.priority];
                const PIcon = pcfg.icon;

                // Editing this existing row
                if (editingId === f.id && draft) return <EditRow key={f.id} flagNo={f.flagNo} />;

                return (
                  <tr key={f.id}
                    className={`group hover:bg-muted/30 transition-colors ${
                      f.priority === 'HIGH' && f.status === 'Open' ? 'bg-red-50/30' : ''
                    }`}>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-1.5">
                        <span className="text-xs font-mono font-semibold bg-muted px-1.5 py-0.5 rounded">{f.flagNo}</span>
                        {f.autoGenerated && <span title="Auto-generated" className="text-xs text-blue-500">auto</span>}
                      </div>
                    </td>
                    <td className="px-3 py-3">
                      <div className="flex items-center gap-1.5">
                        <PIcon className={`w-3.5 h-3.5 ${pcfg.color}`} />
                        <Badge variant={pcfg.variant as Parameters<typeof Badge>[0]['variant']} className="text-xs">{f.priority}</Badge>
                      </div>
                    </td>
                    <td className="px-3 py-3">
                      <span className="text-xs bg-muted px-1.5 py-0.5 rounded text-foreground">{f.category}</span>
                    </td>
                    <td className="px-3 py-3 text-xs text-foreground">
                      {f.security
                        ? <><div className="font-medium">{f.security}</div><div className="font-mono">{f.ticker}</div><div className="text-foreground/70">{f.broker}</div></>
                        : <span className="text-foreground/40">—</span>}
                    </td>
                    <td className="px-3 py-3 text-xs text-foreground leading-relaxed">
                      <div>{f.description}</div>
                      {f.notes && <div className="text-foreground/60 mt-0.5 italic">{f.notes}</div>}
                    </td>
                    <td className="px-3 py-3 text-xs text-foreground leading-relaxed">{f.actionRequired}</td>
                    <td className="px-3 py-3 text-center">
                      <button onClick={() => cycleStatus(f.id)} title="Click to cycle status"
                        className="transition-opacity hover:opacity-80">
                        <Badge variant={STATUS_CFG[f.status].variant as Parameters<typeof Badge>[0]['variant']} className="text-xs cursor-pointer">
                          {STATUS_CFG[f.status].label}
                        </Badge>
                      </button>
                    </td>
                    <td className="px-2 py-3">
                      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <Button size="icon-sm" variant="ghost" title="Edit" onClick={() => startEdit(f)}>
                          <Pencil className="w-3.5 h-3.5" />
                        </Button>
                        <Button size="icon-sm" variant="ghost" title="Delete"
                          className="text-red-500 hover:text-red-600 hover:bg-red-50"
                          onClick={() => setDeleteTarget({ id: f.id, label: `${f.flagNo} — ${f.category}` })}>
                          <Trash2 className="w-3.5 h-3.5" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                );
              })}
              {filtered.length === 0 && editingId !== 'new' && (
                <tr>
                  <td colSpan={8} className="px-4 py-8 text-center text-xs text-foreground/60">
                    No flags match the current filters.
                  </td>
                </tr>
              )}
            </tbody>
            <tfoot>
              <tr className="border-t-2 border-border bg-muted/60">
                <td colSpan={7} className="px-4 py-2.5 text-xs font-semibold text-foreground">{filtered.length} flags shown</td>
                <td className="px-3 py-2.5 text-center text-xs">
                  {openCount > 0
                    ? <span className="text-amber-600 font-medium">{openCount} open</span>
                    : <span className="text-green-600 font-medium flex items-center justify-center gap-1"><CheckCircle2 className="w-3.5 h-3.5" /> All resolved</span>}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </StyledCard>

      <p className="text-xs text-foreground">
        Tip: Click the status badge to cycle Open → Resolved → N/A. Click <Pencil className="w-3 h-3 inline" /> to edit inline.
      </p>

      {/* Delete Confirmation */}
      <Dialog open={!!deleteTarget} onOpenChange={() => setDeleteTarget(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-red-600">
              <Trash2 className="w-4 h-4" /> Delete Flag
            </DialogTitle>
          </DialogHeader>
          <div className="rounded-lg bg-red-50 border border-red-200 p-4 text-sm text-red-800">
            <p className="font-semibold mb-1">Permanently delete:</p>
            <p>{deleteTarget?.label}</p>
          </div>
          <DialogFooter>
            <Button variant="secondary" onClick={() => setDeleteTarget(null)}>Cancel</Button>
            <Button variant="destructive" onClick={confirmDelete}>
              <Trash2 className="w-3.5 h-3.5 mr-1" /> Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
