import { StmtRow } from "./EditableStatementTable";

export const buildCcStatementRows = (
  ccAccountDesc: string,
  glAccountDesc: string,
  acct1AdjustedBalance: string,
  acct2AdjustedBalance: string,
  differenceValue: string,
  showDifference: boolean
): StmtRow[] => [
  { id: "cc-s1", type: "section-header", sectionLabel: `Credit Card Account (${ccAccountDesc})` },
  { id: "cc-ob", type: "data-colSpan", date: "01/12/2024", description: "Balance as per credit card statement, December 31, 2024 — Opening Balance", total: "8,920.00" },
  { id: "cc-d1", type: "data", date: "07/12/2024", description: "Purchase — Office Supplies", transactionType: "Charge", amount: "1,245.00", total: "" },
  { id: "cc-d2", type: "data", date: "14/12/2024", description: "Purchase — Software License", transactionType: "Charge", amount: "599.00", total: "" },
  { id: "cc-d3", type: "data", date: "20/12/2024", description: "Payment received", transactionType: "Payment", amount: "", total: "" },
  { id: "cc-sub1", type: "subtotal", subtotalValue: "10,764.00" },
  { id: "cc-lbl1", type: "label-only", description: "Pending charges not on statement" },
  { id: "cc-p1", type: "data", date: "19/12/2024", description: "Travel Expense — Delta Airlines", transactionType: "Charge", amount: "886.00", total: "", indented: true },
  { id: "cc-adj1", type: "adjusted-balance", balanceLabel: "Adjusted Credit Card Balance", balanceValue: acct1AdjustedBalance },
  // Account 2
  { id: "cc-s2", type: "section-header", sectionLabel: `General Ledger Account (${glAccountDesc})` },
  { id: "cc-ob2", type: "data-colSpan", date: "01/12/2024", description: "Balance as per general ledger, December 31, 2024 — Opening Balance", total: "8,620.00" },
  { id: "cc-d4", type: "data", date: "07/12/2024", description: "Office Supplies recorded in GL", transactionType: "Charge", amount: "1,245.00", total: "" },
  { id: "cc-d5", type: "data", date: "14/12/2024", description: "Software License recorded in GL", transactionType: "Charge", amount: "599.00", total: "1,844.00" },
  { id: "cc-sub2", type: "subtotal", subtotalValue: "10,464.00" },
  { id: "cc-lbl2", type: "label-only", description: "Unrecorded charges in GL" },
  { id: "cc-ded1", type: "data", date: "31/12/2024", description: "Annual fee charged", transactionType: "Fee", amount: "150.00", total: "" },
  { id: "cc-ded2", type: "data", date: "31/12/2024", description: "Interest charges — December", transactionType: "Interest", amount: "86.00", total: "" },
  { id: "cc-ded3", type: "data", date: "28/12/2024", description: "Foreign transaction fee", transactionType: "Fee", amount: "45.00", total: "" },
  { id: "cc-ded4", type: "data", date: "25/12/2024", description: "Late payment penalty", transactionType: "Penalty", amount: "105.00", total: "(386.00)" },
  { id: "cc-adj2", type: "adjusted-balance", balanceLabel: "Adjusted as per Trial Balance", balanceValue: acct2AdjustedBalance },
  ...(showDifference ? [{ id: "cc-diff", type: "difference" as const, differenceValue }] : []),
];

export const buildBankStatementRows = (
  acct1AdjustedBalance: string,
  acct2AdjustedBalance: string,
  differenceValue: string,
  showDifference: boolean
): StmtRow[] => [
  { id: "bk-s1", type: "section-header", sectionLabel: "Bank Account (Chase Checking *4498)" },
  { id: "bk-ob", type: "data-colSpan", date: "31/01/2024", description: "Balance as per bank statement, January 31, 2024 — Opening Balance", total: "10,000.00" },
  { id: "bk-d1", type: "data", date: "30/01/2024", description: "Deposit in transit", transactionType: "Deposit", amount: "", total: "822.00" },
  { id: "bk-sub1", type: "subtotal", subtotalValue: "10,822.00" },
  { id: "bk-lbl1", type: "label-only", description: "Outstanding checks" },
  { id: "bk-chk1", type: "data", date: "15/01/2024", description: "Check No. 201", transactionType: "Check", amount: "200.00", total: "", indented: true },
  { id: "bk-chk2", type: "data", date: "22/01/2024", description: "Check No. 212", transactionType: "Check", amount: "20.00", total: "", indented: true },
  { id: "bk-chk3", type: "data", date: "28/01/2024", description: "Check No. 216", transactionType: "Check", amount: "610.00", total: "(830.00)", indented: true },
  { id: "bk-adj1", type: "adjusted-balance", balanceLabel: "Adjusted Bank Balance", balanceValue: acct1AdjustedBalance },
  // Account 2
  { id: "bk-s2", type: "section-header", sectionLabel: "Trial Balance Account (Chase Other Savings *2422)" },
  { id: "bk-ob2", type: "data-colSpan", date: "31/01/2024", description: "Balance as per depositor's record, January 31, 2024 — Opening Balance", total: "7,525.00" },
  { id: "bk-d2", type: "data", date: "25/01/2024", description: "Note receivable collected by bank", transactionType: "Collection", amount: "1,588.00", total: "" },
  { id: "bk-d3", type: "data", date: "31/01/2024", description: "Interest earned during January", transactionType: "Interest", amount: "50.00", total: "1,638.00" },
  { id: "bk-sub2", type: "subtotal", subtotalValue: "9,163.00" },
  { id: "bk-ded1", type: "data", date: "31/01/2024", description: "Collection charges", transactionType: "Bank Fee", amount: "10.00", total: "" },
  { id: "bk-ded2", type: "data", date: "29/01/2024", description: "NSF check", transactionType: "NSF", amount: "100.00", total: "" },
  { id: "bk-ded3", type: "data", date: "31/01/2024", description: "Service charges", transactionType: "Bank Fee", amount: "25.00", total: "" },
  { id: "bk-ded4", type: "data", date: "20/01/2024", description: "Error on check no. 220", transactionType: "Adjustment", amount: "36.00", total: "(171.00)" },
  { id: "bk-adj2", type: "adjusted-balance", balanceLabel: "Adjusted as per Trial Balance", balanceValue: acct2AdjustedBalance },
  ...(showDifference ? [{ id: "bk-diff", type: "difference" as const, differenceValue }] : []),
];

export const buildIcStatementRows = (
  account1Desc: string,
  account2Desc: string,
  counterpartyEntity: string,
  acct1AdjustedBalance: string,
  acct2AdjustedBalance: string,
  differenceValue: string,
  showDifference: boolean
): StmtRow[] => [
  { id: "ic-s1", type: "section-header", sectionLabel: `Account 1 — IC Receivable (${account1Desc})` },
  { id: "ic-ob", type: "data-colSpan", date: "01/01/2024", description: "Opening Balance — IC Receivable, January 1, 2024", total: "198,400.00" },
  { id: "ic-d1", type: "data", date: "15/03/2024", description: "Management Fee — Q1", transactionType: "IC Charge", amount: "12,800.00", total: "" },
  { id: "ic-d2", type: "data", date: "30/06/2024", description: "License Royalty — H1", transactionType: "IC Charge", amount: "9,600.00", total: "" },
  { id: "ic-d3", type: "data", date: "15/09/2024", description: "Management Fee — Q3", transactionType: "IC Charge", amount: "12,800.00", total: "" },
  { id: "ic-d4", type: "data", date: "31/12/2024", description: "Management Fee — Q4", transactionType: "IC Charge", amount: "3,200.00", total: "" },
  { id: "ic-d5", type: "data", date: "30/11/2024", description: "License Royalty — Nov", transactionType: "IC Charge", amount: "1,800.00", total: "" },
  { id: "ic-d6", type: "data", date: "31/12/2024", description: "Cost Allocation Adj", transactionType: "Adjustment", amount: "950.00", total: "" },
  { id: "ic-d7", type: "data", date: "31/12/2024", description: "Shared Services — Dec", transactionType: "IC Charge", amount: "1,100.00", total: "" },
  { id: "ic-d8", type: "data", date: "31/12/2024", description: "FX Revaluation Diff", transactionType: "Adjustment", amount: "450.00", total: "" },
  { id: "ic-settle", type: "data", date: "30/06/2024", description: "Settlement Payment — H1", transactionType: "Payment", amount: "(15,500.00)", total: "" },
  { id: "ic-sub1", type: "subtotal", subtotalValue: "225,600.00" },
  { id: "ic-lbl1", type: "label-only", description: "Unrecorded inter-company charges" },
  { id: "ic-p1", type: "data", date: "31/12/2024", description: "Year-end reclass — IC clearing", transactionType: "Reclassification", amount: "20,200.00", total: "", indented: true },
  { id: "ic-adj1", type: "adjusted-balance", balanceLabel: "Adjusted IC Receivable Balance", balanceValue: acct1AdjustedBalance },
  // Account 2
  { id: "ic-s2", type: "section-header", sectionLabel: `Account 2 — IC Payable (${account2Desc}, ${counterpartyEntity})` },
  { id: "ic-ob2", type: "data-colSpan", date: "01/01/2024", description: "Opening Balance — IC Payable, January 1, 2024", total: "198,400.00" },
  { id: "ic-d9", type: "data", date: "15/03/2024", description: "Management Fee received — Q1", transactionType: "IC Charge", amount: "12,800.00", total: "" },
  { id: "ic-d10", type: "data", date: "30/06/2024", description: "License Royalty received — H1", transactionType: "IC Charge", amount: "9,600.00", total: "" },
  { id: "ic-d11", type: "data", date: "15/09/2024", description: "Management Fee received — Q3", transactionType: "IC Charge", amount: "12,800.00", total: "" },
  { id: "ic-settle2", type: "data", date: "30/06/2024", description: "Settlement Payment — H1", transactionType: "Payment", amount: "(15,500.00)", total: "" },
  { id: "ic-sub2", type: "subtotal", subtotalValue: "218,100.00" },
  { id: "ic-lbl2", type: "label-only", description: "Unrecorded IC charges on counterparty" },
  { id: "ic-ud1", type: "data", date: "31/12/2024", description: "Management Fee — Q4 (not recorded)", transactionType: "IC Charge", amount: "3,200.00", total: "" },
  { id: "ic-ud2", type: "data", date: "30/11/2024", description: "License Royalty — Nov (not recorded)", transactionType: "IC Charge", amount: "1,800.00", total: "" },
  { id: "ic-ud3", type: "data", date: "31/12/2024", description: "Cost Allocation Adj (not recorded)", transactionType: "Adjustment", amount: "950.00", total: "" },
  { id: "ic-ud4", type: "data", date: "31/12/2024", description: "Shared Services — Dec (not recorded)", transactionType: "IC Charge", amount: "1,100.00", total: "" },
  { id: "ic-ud5", type: "data", date: "31/12/2024", description: "FX Revaluation Diff (not recorded)", transactionType: "Adjustment", amount: "450.00", total: "(7,500.00)" },
  { id: "ic-adj2", type: "adjusted-balance", balanceLabel: "Adjusted IC Payable Balance", balanceValue: acct2AdjustedBalance },
  ...(showDifference ? [{ id: "ic-diff", type: "difference" as const, differenceValue }] : []),
];
